import type { Activity, Goal } from '../types'

export const mockActivities: Activity[] = [
  {
    id: '1',
    strava_id: 12345678901,
    user_id: 'user-1',
    name: 'Morning Easy Run',
    type: 'Run',
    sport_type: 'Run',
    start_date: '2026-04-06T07:30:00Z',
    elapsed_time: 2820,
    moving_time: 2700,
    distance: 7520,
    total_elevation_gain: 42,
    average_speed: 2.79,
    max_speed: 3.8,
    average_heartrate: 142,
    max_heartrate: 158,
    calories: 520,
    suffer_score: 62,
    average_cadence: 172,
    average_watts: null,
    map_polyline: null,
    ai_analysis: `## Effort Summary\nThis was a well-paced easy run — your heart rate stayed comfortably in Zone 2 for most of the session, which is exactly where you want to be for aerobic base building.\n\n## Pacing\nYou maintained a consistent 5:59/km pace throughout, with only minor variation between splits. The slight positive split in the last km is completely normal for an easy effort.\n\n## Heart Rate Zones\n- **Zone 1 (Recovery):** 8%\n- **Zone 2 (Aerobic):** 74%\n- **Zone 3 (Tempo):** 18%\n\n## What Went Well\n- Excellent discipline keeping the pace easy\n- Cadence at 172 spm is solid — reduces ground contact time\n- Good consistency across all splits\n\n## What to Improve\n- Consider starting 10-15 sec/km slower for the first km to avoid the Zone 3 time in the early minutes\n- Your cadence dropped slightly in the last km — focus on maintaining quick turnover even when fatigued`,
    raw_data: {},
    created_at: '2026-04-06T08:20:00Z',
  },
  {
    id: '2',
    strava_id: 12345678902,
    user_id: 'user-1',
    name: 'Interval Session — 6x800m',
    type: 'Run',
    sport_type: 'Run',
    start_date: '2026-04-04T17:00:00Z',
    elapsed_time: 3600,
    moving_time: 3420,
    distance: 9800,
    total_elevation_gain: 28,
    average_speed: 2.86,
    max_speed: 4.5,
    average_heartrate: 165,
    max_heartrate: 186,
    calories: 780,
    suffer_score: 142,
    average_cadence: 178,
    average_watts: null,
    map_polyline: null,
    ai_analysis: `## Effort Summary\nA demanding interval session with 6x800m repeats. Your effort distribution was aggressive but controlled — the last two reps were slightly slower but you held form well.\n\n## Pacing\nRep paces ranged from 3:28/km to 3:42/km. The 14-second spread is acceptable for this workout. Recovery jogs averaged 5:45/km.\n\n## Heart Rate Zones\n- **Zone 3 (Tempo):** 22%\n- **Zone 4 (Threshold):** 45%\n- **Zone 5 (VO2max):** 33%\n\n## What Went Well\n- Strong commitment to the workout — no reps cut short\n- Recovery HR dropped well between reps (good aerobic fitness indicator)\n- Peak cadence of 184 during fast reps shows good neuromuscular response\n\n## What to Improve\n- Try to keep the first rep closer to target pace instead of going out hot\n- Consider extending recovery jog by 15-30 seconds if needed to maintain rep quality`,
    raw_data: {},
    created_at: '2026-04-04T18:10:00Z',
  },
  {
    id: '3',
    strava_id: 12345678903,
    user_id: 'user-1',
    name: 'Sunday Long Ride',
    type: 'Ride',
    sport_type: 'Ride',
    start_date: '2026-04-05T09:00:00Z',
    elapsed_time: 7200,
    moving_time: 6840,
    distance: 52300,
    total_elevation_gain: 380,
    average_speed: 7.65,
    max_speed: 12.2,
    average_heartrate: 138,
    max_heartrate: 172,
    calories: 1420,
    suffer_score: 98,
    average_cadence: 82,
    average_watts: 185,
    map_polyline: null,
    ai_analysis: `## Effort Summary\nA solid endurance ride with good aerobic stimulus. You spent the majority of the ride in Zone 2 with some Zone 3 pushes on the climbs.\n\n## Power & Pacing\nAverage power of 185W is appropriate for a long aerobic ride. Normalized power was likely around 195W given the terrain variation.\n\n## Heart Rate Zones\n- **Zone 1 (Recovery):** 5%\n- **Zone 2 (Aerobic):** 68%\n- **Zone 3 (Tempo):** 24%\n- **Zone 4 (Threshold):** 3%\n\n## What Went Well\n- Great fueling discipline — consistent effort throughout suggests good energy management\n- Cadence stayed in the efficient 80-85 range\n- 380m of climbing at this distance shows good route selection for building strength\n\n## What to Improve\n- On the steeper climbs, try to stay seated more to build hip flexor strength\n- Consider adding 2-3 tempo intervals of 10 min next time to add training stimulus`,
    raw_data: {},
    created_at: '2026-04-05T11:05:00Z',
  },
  {
    id: '4',
    strava_id: 12345678904,
    user_id: 'user-1',
    name: 'Pool Swim — Technique Focus',
    type: 'Swim',
    sport_type: 'Swim',
    start_date: '2026-04-03T12:00:00Z',
    elapsed_time: 3000,
    moving_time: 2700,
    distance: 2200,
    total_elevation_gain: 0,
    average_speed: 0.81,
    max_speed: 1.2,
    average_heartrate: 132,
    max_heartrate: 155,
    calories: 380,
    suffer_score: 45,
    average_cadence: null,
    average_watts: null,
    map_polyline: null,
    ai_analysis: `## Effort Summary\nA good technique-focused swim session. The moderate heart rate suggests you prioritized form over speed, which is the right approach for these sessions.\n\n## Pacing\nAverage pace of 2:03/100m with a good range between drill sets (2:20) and main sets (1:48). This spread suggests you're effectively differentiating between technique and effort work.\n\n## What Went Well\n- Distance covered is solid for a technique session\n- Heart rate stayed controlled — didn't turn it into an endurance session\n- Good session structure mixing drills with main sets\n\n## What to Improve\n- Try adding some single-arm drill sets to address any bilateral imbalances\n- Consider using a pull buoy for 400m to isolate upper body catch mechanics`,
    raw_data: {},
    created_at: '2026-04-03T12:52:00Z',
  },
  {
    id: '5',
    strava_id: 12345678905,
    user_id: 'user-1',
    name: 'Upper Body Strength',
    type: 'WeightTraining',
    sport_type: 'WeightTraining',
    start_date: '2026-04-02T16:30:00Z',
    elapsed_time: 3600,
    moving_time: 3300,
    distance: 0,
    total_elevation_gain: 0,
    average_speed: 0,
    max_speed: 0,
    average_heartrate: 118,
    max_heartrate: 145,
    calories: 320,
    suffer_score: 38,
    average_cadence: null,
    average_watts: null,
    map_polyline: null,
    ai_analysis: `## Effort Summary\nA focused strength session targeting upper body. Heart rate data suggests appropriate rest periods between sets with good work intensity during sets.\n\n## What Went Well\n- Session duration of 60 minutes is ideal for a focused strength block\n- Heart rate recovery between sets looks good — well-rested between efforts\n- Consistent session — no signs of early fatigue cutting the workout short\n\n## What to Improve\n- Consider adding a brief mobility cool-down to support recovery\n- If this is supplementary to endurance training, ensure you're not going to failure — leave 1-2 reps in reserve`,
    raw_data: {},
    created_at: '2026-04-02T17:32:00Z',
  },
  {
    id: '6',
    strava_id: 12345678906,
    user_id: 'user-1',
    name: 'Recovery Jog',
    type: 'Run',
    sport_type: 'Run',
    start_date: '2026-04-01T08:00:00Z',
    elapsed_time: 1800,
    moving_time: 1740,
    distance: 4200,
    total_elevation_gain: 15,
    average_speed: 2.41,
    max_speed: 3.1,
    average_heartrate: 128,
    max_heartrate: 140,
    calories: 280,
    suffer_score: 22,
    average_cadence: 168,
    average_watts: null,
    map_polyline: null,
    ai_analysis: `## Effort Summary\nA true recovery run — well executed. Heart rate stayed firmly in Zone 1-2, which is exactly right for active recovery.\n\n## Pacing\nSteady 6:54/km pace. No surges, no drift. This is how recovery runs should look.\n\n## What Went Well\n- Excellent heart rate discipline — never crept above 140\n- Short duration was the right call for a recovery day\n- Consistent pace shows good body awareness\n\n## What to Improve\n- Nothing — this is textbook recovery running. Keep doing this after hard sessions.`,
    raw_data: {},
    created_at: '2026-04-01T08:32:00Z',
  },
]

export const mockGoals: Goal[] = [
  {
    id: '1',
    user_id: 'user-1',
    event_type: 'Run',
    event_name: 'Copenhagen Half Marathon',
    target_date: '2026-05-17',
    target_distance: 21097.5,
    target_time: 5400, // 1:30:00
    target_pace: 256, // 4:16/km
    status: 'active',
    training_plan: [
      {
        week: 1,
        focus: 'Base Building & Assessment',
        sessions: [
          { day: 'Monday', type: 'Easy Run', description: 'Easy aerobic run. Keep HR in Zone 2. Focus on relaxed form.', duration_minutes: 45, intensity: 'easy' },
          { day: 'Tuesday', type: 'Strength', description: 'Lower body strength: squats, lunges, calf raises. 3x10 each.', duration_minutes: 40, intensity: 'moderate' },
          { day: 'Wednesday', type: 'Intervals', description: '8x400m at target HM pace (4:16/km) with 90s jog recovery.', duration_minutes: 50, intensity: 'hard' },
          { day: 'Thursday', type: 'Rest', description: 'Complete rest or light stretching/yoga.', duration_minutes: 0, intensity: 'recovery' },
          { day: 'Friday', type: 'Tempo Run', description: '15 min easy, 20 min at tempo (4:30-4:40/km), 10 min easy.', duration_minutes: 45, intensity: 'hard' },
          { day: 'Saturday', type: 'Easy Run', description: 'Short easy shakeout. Keep it conversational.', duration_minutes: 30, intensity: 'easy' },
          { day: 'Sunday', type: 'Long Run', description: '16km at easy pace (5:30-6:00/km). Practice fueling.', duration_minutes: 90, intensity: 'moderate' },
        ],
      },
      {
        week: 2,
        focus: 'Building Threshold Endurance',
        sessions: [
          { day: 'Monday', type: 'Easy Run', description: 'Recovery-paced run. Shake out the legs from Sunday.', duration_minutes: 40, intensity: 'easy' },
          { day: 'Tuesday', type: 'Hill Repeats', description: '6x90s hill sprints at hard effort. Jog down for recovery.', duration_minutes: 45, intensity: 'hard' },
          { day: 'Wednesday', type: 'Rest', description: 'Rest day. Light mobility work if feeling stiff.', duration_minutes: 0, intensity: 'recovery' },
          { day: 'Thursday', type: 'Tempo Run', description: '10 min easy, 25 min at tempo, 10 min easy.', duration_minutes: 45, intensity: 'hard' },
          { day: 'Friday', type: 'Easy Run', description: 'Easy 35 min with 4x100m strides at the end.', duration_minutes: 35, intensity: 'easy' },
          { day: 'Saturday', type: 'Strength', description: 'Full body circuit: planks, bridges, single-leg work.', duration_minutes: 35, intensity: 'moderate' },
          { day: 'Sunday', type: 'Long Run', description: '18km with last 4km at HM pace.', duration_minutes: 100, intensity: 'moderate' },
        ],
      },
      {
        week: 3,
        focus: 'Race-Specific Speed',
        sessions: [
          { day: 'Monday', type: 'Easy Run', description: 'Easy 40 min. Focus on cadence — aim for 170+ spm.', duration_minutes: 40, intensity: 'easy' },
          { day: 'Tuesday', type: 'Intervals', description: '5x1000m at 4:10/km with 2 min recovery. Key speed session.', duration_minutes: 55, intensity: 'hard' },
          { day: 'Wednesday', type: 'Cross-Train', description: 'Swim or bike for 45 min. Active recovery for legs.', duration_minutes: 45, intensity: 'easy' },
          { day: 'Thursday', type: 'Tempo Run', description: '10 min easy, 30 min at HM pace (4:16/km), 5 min easy.', duration_minutes: 45, intensity: 'hard' },
          { day: 'Friday', type: 'Rest', description: 'Complete rest.', duration_minutes: 0, intensity: 'recovery' },
          { day: 'Saturday', type: 'Easy Run', description: 'Easy 30 min with strides.', duration_minutes: 30, intensity: 'easy' },
          { day: 'Sunday', type: 'Long Run', description: '20km — longest run. First 14km easy, last 6km at HM pace.', duration_minutes: 110, intensity: 'moderate' },
        ],
      },
      {
        week: 4,
        focus: 'Taper & Race Prep',
        sessions: [
          { day: 'Monday', type: 'Easy Run', description: 'Easy 35 min. Begin reducing volume.', duration_minutes: 35, intensity: 'easy' },
          { day: 'Tuesday', type: 'Sharpener', description: '4x800m at slightly faster than HM pace. Stay sharp, don\'t strain.', duration_minutes: 40, intensity: 'hard' },
          { day: 'Wednesday', type: 'Rest', description: 'Rest. Hydrate well, prioritize sleep.', duration_minutes: 0, intensity: 'recovery' },
          { day: 'Thursday', type: 'Easy Run', description: '25 min easy with 4x100m strides.', duration_minutes: 25, intensity: 'easy' },
          { day: 'Friday', type: 'Rest', description: 'Complete rest. Lay out race gear. Visualize the race.', duration_minutes: 0, intensity: 'recovery' },
          { day: 'Saturday', type: 'Shakeout', description: '15 min very easy jog. A few strides. Stay loose.', duration_minutes: 15, intensity: 'recovery' },
          { day: 'Sunday', type: 'Race Day', description: 'Copenhagen Half Marathon. Target: 1:30:00. Go get it.', duration_minutes: 90, intensity: 'hard' },
        ],
      },
    ],
    created_at: '2026-04-01T10:00:00Z',
  },
  {
    id: '2',
    user_id: 'user-1',
    event_type: 'Ride',
    event_name: 'Century Ride Challenge',
    target_date: '2026-06-20',
    target_distance: 160934, // 100 miles
    target_time: 18000, // 5:00:00
    target_pace: 112, // ~1:52/km
    status: 'active',
    training_plan: null,
    created_at: '2026-03-15T10:00:00Z',
  },
]
